# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"auto_str": "01_data.loader.ipynb",
         "ObjectFactory": "01_data.loader.ipynb",
         "DbSinkProvider": "01_data.loader.ipynb",
         "FileSourceProvider": "01_data.loader.ipynb",
         "PgSqlDbBuilder": "01_data.loader.ipynb",
         "PgSqlDb": "01_data.loader.ipynb",
         "ExcelSource": "01_data.loader.ipynb",
         "supported_databases": "01_data.loader.ipynb",
         "supported_files_types": "01_data.loader.ipynb",
         "ingest": "01_data.loader.ipynb"}

modules = ["data/loader.py"]

doc_url = "https://alpah2phi.github.io/alphalib/"

git_url = "https://github.com/alpah2phi/alphalib/tree/master/"

def custom_doc_links(name): return None
