repository: alpha2phi/alphalib
output: web
topnav_title: alphalib
site_title: alphalib
company_name: alpha2phi
github_editme_path:
use_math: true
#google_analytics:
#google_search:

exclude:
  - .idea/
  - .gitignore
  - vendor

feedback_disable: true

highlighter: rouge

markdown: kramdown
kramdown:
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

default_badges:
  colab: true

collections:
  tooltips:
    output: false
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

sidebars:
- home_sidebar

description: "Documentation for alphalib"
# theme: jekyll-theme-cayman

baseurl: /alphalib/